name: pickiverse_app
description: Pickiverse Application
version: 1.0.0+3
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_card_swiper: ^7.0.2
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  freezed_annotation: ^2.4.4
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/
    - assets/app_icons/
    - assets/splash/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/app_icons/production.png"
  image_path_ios: "assets/app_icons/production.png"

  # Development
  development:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path_android: "assets/app_icons/development.png"
    image_path_ios: "assets/app_icons/development.png"
    flavor: development

  # Staging
  staging:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path_android: "assets/app_icons/staging.png"
    image_path_ios: "assets/app_icons/staging.png"
    flavor: staging

  # Production
  production:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path_android: "assets/app_icons/production.png"
    image_path_ios: "assets/app_icons/production.png"
    flavor: production

# Default splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash/title_black.png"
  color_dark: "#121212"
  image_dark: "assets/splash/title_white.png"
  fullscreen: true

  android_12:
    color: "#FFFFFF"
    image: "assets/splash/title_center.png"
    color_dark: "#121212"
    image_dark: "assets/splash/title_center.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#121212"

  web: false
  ios: true
  android: true

# Development flavor splash screen
flutter_native_splash-development:
  color: "#FFFFFF"
  image: "assets/splash/title_black.png"
  color_dark: "#121212"
  image_dark: "assets/splash/title_white.png"
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: "assets/splash/title_center.png"
    color_dark: "#121212"
    image_dark: "assets/splash/title_center.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#121212"
  web: false
  ios: true
  android: true
  flavor: development

# Staging flavor splash screen
flutter_native_splash-staging:
  color: "#FFFFFF"
  image: "assets/splash/title_black.png"
  color_dark: "#121212"
  image_dark: "assets/splash/title_white.png"
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: "assets/splash/title_center.png"
    color_dark: "#121212"
    image_dark: "assets/splash/title_center.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#121212"
  web: false
  ios: true
  android: true
  flavor: staging

# Production flavor splash screen
flutter_native_splash-production:
  color: "#FFFFFF"
  image: "assets/splash/title_black.png"
  color_dark: "#121212"
  image_dark: "assets/splash/title_white.png"
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: "assets/splash/title_center.png"
    color_dark: "#121212"
    image_dark: "assets/splash/title_center.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#121212"
  web: false
  ios: true
  android: true
  flavor: production
