import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF2196F3), // Blue
  onPrimary: Colors.white,
  primaryContainer: Color(0xFFE3F2FD),
  onPrimaryContainer: Color(0xFF1565C0),
  secondary: Color(0xFF03A9F4), // Light Blue
  onSecondary: Colors.white,
  secondaryContainer: Color(0xFFE1F5FE),
  onSecondaryContainer: Color(0xFF0277BD),
  tertiary: Color(0xFF00BCD4), // Cyan
  onTertiary: Colors.white,
  tertiaryContainer: Color(0xFFE0F7FA),
  onTertiaryContainer: Color(0xFF006064),
  error: Color(0xFFB00020),
  onError: Colors.white,
  errorContainer: Color(0xFFFDE7E9),
  onErrorContainer: Color(0xFF601410),
  surface: Colors.white,
  onSurface: Colors.black,
  onSurfaceVariant: Color(0xFF121212),
  outline: Color(0xFFE0E0E0),
  outlineVariant: Color(0xFFBDBDBD),
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: Colors.black,
  onInverseSurface: Colors.white,
  inversePrimary: Color(0xFF90CAF9),
  surfaceTint: Color(0xFF2196F3),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF90CAF9),
  onPrimary: Colors.black,
  primaryContainer: Color(0xFF1565C0),
  onPrimaryContainer: Color(0xFFE3F2FD),
  secondary: Color(0xFF81D4FA),
  onSecondary: Colors.black,
  secondaryContainer: Color(0xFF0277BD),
  onSecondaryContainer: Color(0xFFE1F5FE),
  tertiary: Color(0xFF80DEEA),
  onTertiary: Colors.black,
  tertiaryContainer: Color(0xFF006064),
  onTertiaryContainer: Color(0xFFE0F7FA),
  error: Color(0xFFCF6679),
  onError: Colors.black,
  errorContainer: Color(0xFF8B0000),
  onErrorContainer: Color(0xFFFFDAD6),
  surface: Color(0xFF1E1E1E),
  onSurface: Color(0xFFE0E0E0),
  onSurfaceVariant: Color(0xFFE0E0E0),
  outline: Color(0xFF3D3D3D),
  outlineVariant: Color(0xFF757575),
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: Colors.white,
  onInverseSurface: Colors.black,
  inversePrimary: Color(0xFF1976D2),
  surfaceTint: Color(0xFF90CAF9),
);
